version: '3'
services:
  admin-service-bssn:
    image: admin-service-bssn
    build: 
      context: .
      dockerfile: Dockerfile.admin-service
    restart: always
    expose:
      - "5050"
    ports:
      - "5050:5050"
  fp-service-bssn:
    image: fp-service-bssn
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    volumes:
      - ~/uploads-bssn:/uploads
  frontend-bssn:
    image: frontend-bssn
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "5080:80"
      - "5443:443"